#对外端口
server:
  port: 9001

spring:
  #微服务配置
  cloud:
    nacos:
      discovery:
        #server-addr: 106.12.105.123:8848
        server-addr: 127.0.0.1:8848
  application:
    name: api-gateway
  # 数据库配置
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3300/framework_sample_starter?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456

zuul:
  ribbon-isolation-strategy: thread
  ribbon:
    eager-load:
      enabled: true
    threadPool:
      useSeparateThreadPools: true
      threadPoolKeyPrefix: api-gateway
  #关闭重试
  retryable: false
  #/oauth/token需要请求头处理
  sensitive-headers:
  ignored-headers: Access-Control-Allow-Credentials,Access-Control-Allow-Origin,Access-Control-Allow-Methods
  add-host-header: true
  routes:
    user-center-process:
      path: /api/user-center/**
      service-id: demo-api
      strip-prefix: true
      custom-sensitive-headers: true
    auth:
      path: /api/auth/**
      service-id: auth-api
      strip-prefix: true
      custom-sensitive-headers: true
  ssl-hostname-validation-enabled: false

security:
  ignore:
    url: /auth/login###/auth/register###/auth/login-get-user###/mock/###/guest/###/monitor-center/


#swagger:
#  butler:
#    api-docs-path:  v2/api-docs
#    swagger-version: 2.0
#    auto-generate-from-zuul-routes: true
#    generate-routes: auth


#mybatis-plus默认配置
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  #类别名，支持通配符 * 或者 ; 分割
  typeAliasesPackage: com.weng.**.mapper
